// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerspectiveAPI.Data;

#nullable disable

namespace PerspectiveAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220719130500_slug")]
    partial class slug
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PerspectiveAPI.Models.Domain.Post", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePhysicalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimePosted")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = "1",
                            AuthorId = "1",
                            Header = "Первый пост",
                            RawHtml = "<h1>Это реальный пост, ребята</h1>",
                            Slug = "pervyii-post",
                            TimePosted = new DateTime(2022, 7, 19, 13, 4, 58, 960, DateTimeKind.Utc).AddTicks(5977)
                        },
                        new
                        {
                            PostId = "2",
                            AuthorId = "1",
                            Header = "Второй post",
                            RawHtml = "<hr /> <h5>Это реально???</h5> <h1>Да, это реально)</h1>",
                            Slug = "vtoroii-post",
                            TimePosted = new DateTime(2022, 7, 19, 13, 4, 58, 960, DateTimeKind.Utc).AddTicks(6386)
                        });
                });

            modelBuilder.Entity("PerspectiveAPI.Models.Domain.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            Password = "AQinvNmfummuRGFenlQuSUmbEGAJcJEVfCFJhEoZmSo=",
                            Role = 2,
                            Salt = new byte[] { 222, 95, 214, 19, 9, 63, 115, 211, 78, 67, 250, 148, 110, 196, 15, 156 },
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = "2",
                            Password = "zoc13OoaNLuSlntigT7e21ohl/FhQzSoevPeldseanE=",
                            Role = 0,
                            Salt = new byte[] { 182, 31, 96, 175, 15, 1, 108, 51, 114, 77, 146, 240, 96, 113, 45, 115 },
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("PerspectiveAPI.Models.Domain.Post", b =>
                {
                    b.HasOne("PerspectiveAPI.Models.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
