// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerspectiveAPI.Data;

#nullable disable

namespace PerspectiveAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PerspectiveAPI.Models.Domain.Post", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePhysicalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimePosted")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = "1",
                            AuthorId = "1",
                            Header = "Первый пост",
                            RawHtml = "<h1>Это реальный пост, ребята</h1>",
                            Slug = "",
                            TimePosted = new DateTime(2022, 7, 18, 20, 52, 29, 638, DateTimeKind.Utc).AddTicks(5355)
                        },
                        new
                        {
                            PostId = "2",
                            AuthorId = "1",
                            Header = "Второй post",
                            RawHtml = "<hr /> <h5>Это реально???</h5> <h1>Да, это реально)</h1>",
                            Slug = "post",
                            TimePosted = new DateTime(2022, 7, 18, 20, 52, 29, 638, DateTimeKind.Utc).AddTicks(5365)
                        });
                });

            modelBuilder.Entity("PerspectiveAPI.Models.Domain.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            Password = "0nVoGnjW1MQxrpfzVFdBTI9tfEcxCBLy1Fj+VSiYasU=",
                            Role = 2,
                            Salt = new byte[] { 171, 200, 180, 49, 131, 105, 71, 213, 138, 40, 223, 149, 97, 42, 139, 84 },
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = "2",
                            Password = "RmaY7A7j0RjwdJOJ4aNmCoRLCpmkKXA3+nJmOr4VZfQ=",
                            Role = 0,
                            Salt = new byte[] { 48, 58, 18, 9, 215, 27, 241, 208, 194, 63, 62, 99, 26, 7, 132, 102 },
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("PerspectiveAPI.Models.Domain.Post", b =>
                {
                    b.HasOne("PerspectiveAPI.Models.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
